### ISSUE TITLE
Unhandled Promise error

### ISSUE THREAD

**Issue by sboozy** [sboozy/MovieUserCrudApp#1]
I have an unhandled promise error and would like to discuss what is happening with that.

**Comment by sboozy** [comment]
My getALL works fine.  My issue is with my getOne.  My error says that I am not handling my promise (even though I see the output of my error handling - saying that we have an error.  JZ and I have spent a considerable amount of time trying to suss this out.  The model works in psql, I can console.log and see that I am getting a req.params.id .  I can't console.log data b/c  .then never runs but who the heck knows why.  Any help would be greatly appreciated.  I'm gonna go watch a video on FlexBox.

**Comment by Jon-zachary** [comment]
The issue was with the pg promise db.one as opposed to db.many. Shout out to Drake for figuring it out.
